[2025-07-06T19:29:00.360+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-06T19:29:00.466+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fin_cotacoes_bcb_classic.transform scheduled__2025-02-01T00:00:00+00:00 [queued]>
[2025-07-06T19:29:00.503+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fin_cotacoes_bcb_classic.transform scheduled__2025-02-01T00:00:00+00:00 [queued]>
[2025-07-06T19:29:00.503+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-07-06T19:29:00.554+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform> on 2025-02-01 00:00:00+00:00
[2025-07-06T19:29:00.595+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=22980) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-06T19:29:00.601+0000] {standard_task_runner.py:63} INFO - Started process 23029 to run task
[2025-07-06T19:29:00.603+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fin_cotacoes_bcb_classic', 'transform', 'scheduled__2025-02-01T00:00:00+00:00', '--job-id', '1036', '--raw', '--subdir', 'DAGS_FOLDER/cotacoes.py', '--cfg-path', '/tmp/tmpvr0fxbpp']
[2025-07-06T19:29:00.604+0000] {standard_task_runner.py:91} INFO - Job 1036: Subtask transform
[2025-07-06T19:29:00.758+0000] {task_command.py:426} INFO - Running <TaskInstance: fin_cotacoes_bcb_classic.transform scheduled__2025-02-01T00:00:00+00:00 [running]> on host 20adb53d65c4
[2025-07-06T19:29:00.989+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fin_cotacoes_bcb_classic' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2025-02-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-01T00:00:00+00:00'
[2025-07-06T19:29:00.991+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-06T19:29:00.991+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-06T19:29:00.992+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/cotacoes.py", line 62, in transform
    cotacoes_csv = kwargs['ti'].xcom_pull(task_id='extract')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TaskInstance.xcom_pull() got an unexpected keyword argument 'task_id'
[2025-07-06T19:29:01.013+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=fin_cotacoes_bcb_classic, task_id=transform, run_id=scheduled__2025-02-01T00:00:00+00:00, execution_date=20250201T000000, start_date=20250706T192900, end_date=20250706T192901
[2025-07-06T19:29:01.041+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1036 for task transform (TaskInstance.xcom_pull() got an unexpected keyword argument 'task_id'; 23029)
[2025-07-06T19:29:01.075+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-06T19:29:01.098+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-07-07T14:12:00.262+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-07T14:12:00.300+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fin_cotacoes_bcb_classic.transform scheduled__2025-02-01T00:00:00+00:00 [queued]>
[2025-07-07T14:12:00.312+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fin_cotacoes_bcb_classic.transform scheduled__2025-02-01T00:00:00+00:00 [queued]>
[2025-07-07T14:12:00.312+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-07-07T14:12:00.322+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform> on 2025-02-01 00:00:00+00:00
[2025-07-07T14:12:00.329+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=65069) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-07T14:12:00.329+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fin_cotacoes_bcb_classic', 'transform', 'scheduled__2025-02-01T00:00:00+00:00', '--job-id', '1866', '--raw', '--subdir', 'DAGS_FOLDER/cotacoes.py', '--cfg-path', '/tmp/tmp93pkm8v_']
[2025-07-07T14:12:00.330+0000] {standard_task_runner.py:63} INFO - Started process 65090 to run task
[2025-07-07T14:12:00.330+0000] {standard_task_runner.py:91} INFO - Job 1866: Subtask transform
[2025-07-07T14:12:00.381+0000] {task_command.py:426} INFO - Running <TaskInstance: fin_cotacoes_bcb_classic.transform scheduled__2025-02-01T00:00:00+00:00 [running]> on host bc96ca91d307
[2025-07-07T14:12:00.461+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fin_cotacoes_bcb_classic' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2025-02-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-01T00:00:00+00:00'
[2025-07-07T14:12:00.462+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-07T14:12:00.470+0000] {cotacoes.py:63} WARNING - Nenhum dado recebido da tarefa de extração. Pulando transformação.
[2025-07-07T14:12:00.470+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-07T14:12:00.470+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-07T14:12:00.479+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=fin_cotacoes_bcb_classic, task_id=transform, run_id=scheduled__2025-02-01T00:00:00+00:00, execution_date=20250201T000000, start_date=20250707T141200, end_date=20250707T141200
[2025-07-07T14:12:00.504+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-07T14:12:00.531+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-07T14:12:00.533+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-07-07T14:20:14.388+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-07T14:20:14.454+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fin_cotacoes_bcb_classic.transform scheduled__2025-02-01T00:00:00+00:00 [queued]>
[2025-07-07T14:20:14.464+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fin_cotacoes_bcb_classic.transform scheduled__2025-02-01T00:00:00+00:00 [queued]>
[2025-07-07T14:20:14.464+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-07-07T14:20:14.483+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform> on 2025-02-01 00:00:00+00:00
[2025-07-07T14:20:14.500+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=69811) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-07T14:20:14.501+0000] {standard_task_runner.py:63} INFO - Started process 69872 to run task
[2025-07-07T14:20:14.506+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fin_cotacoes_bcb_classic', 'transform', 'scheduled__2025-02-01T00:00:00+00:00', '--job-id', '2001', '--raw', '--subdir', 'DAGS_FOLDER/cotacoes.py', '--cfg-path', '/tmp/tmpriqr5yul']
[2025-07-07T14:20:14.507+0000] {standard_task_runner.py:91} INFO - Job 2001: Subtask transform
[2025-07-07T14:20:14.602+0000] {task_command.py:426} INFO - Running <TaskInstance: fin_cotacoes_bcb_classic.transform scheduled__2025-02-01T00:00:00+00:00 [running]> on host bc96ca91d307
[2025-07-07T14:20:14.790+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fin_cotacoes_bcb_classic' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2025-02-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-01T00:00:00+00:00'
[2025-07-07T14:20:14.795+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-07T14:20:14.826+0000] {cotacoes.py:63} WARNING - Nenhum dado recebido da tarefa de extração. Pulando transformação.
[2025-07-07T14:20:14.826+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-07T14:20:14.826+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-07T14:20:14.853+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=fin_cotacoes_bcb_classic, task_id=transform, run_id=scheduled__2025-02-01T00:00:00+00:00, execution_date=20250201T000000, start_date=20250707T142014, end_date=20250707T142014
[2025-07-07T14:20:14.902+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-07T14:20:14.964+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-07T14:20:14.965+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
