[2025-07-06T19:34:18.756+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-06T19:34:18.783+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fin_cotacoes_bcb_classic.transform scheduled__2025-03-03T00:00:00+00:00 [queued]>
[2025-07-06T19:34:18.790+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fin_cotacoes_bcb_classic.transform scheduled__2025-03-03T00:00:00+00:00 [queued]>
[2025-07-06T19:34:18.790+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-07-06T19:34:18.800+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform> on 2025-03-03 00:00:00+00:00
[2025-07-06T19:34:18.810+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2455) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-06T19:34:18.810+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fin_cotacoes_bcb_classic', 'transform', 'scheduled__2025-03-03T00:00:00+00:00', '--job-id', '1100', '--raw', '--subdir', 'DAGS_FOLDER/cotacoes.py', '--cfg-path', '/tmp/tmp1m5yaylj']
[2025-07-06T19:34:18.811+0000] {standard_task_runner.py:91} INFO - Job 1100: Subtask transform
[2025-07-06T19:34:18.811+0000] {standard_task_runner.py:63} INFO - Started process 2460 to run task
[2025-07-06T19:34:18.865+0000] {task_command.py:426} INFO - Running <TaskInstance: fin_cotacoes_bcb_classic.transform scheduled__2025-03-03T00:00:00+00:00 [running]> on host 20adb53d65c4
[2025-07-06T19:34:18.939+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fin_cotacoes_bcb_classic' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-03T00:00:00+00:00'
[2025-07-06T19:34:18.940+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-06T19:34:18.941+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-06T19:34:18.941+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/cotacoes.py", line 62, in transform
    cotacoes_csv = kwargs['ti'].xcom_pull(task_id='extract')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TaskInstance.xcom_pull() got an unexpected keyword argument 'task_id'
[2025-07-06T19:34:18.951+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=fin_cotacoes_bcb_classic, task_id=transform, run_id=scheduled__2025-03-03T00:00:00+00:00, execution_date=20250303T000000, start_date=20250706T193418, end_date=20250706T193418
[2025-07-06T19:34:18.961+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1100 for task transform (TaskInstance.xcom_pull() got an unexpected keyword argument 'task_id'; 2460)
[2025-07-06T19:34:18.986+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-06T19:34:18.995+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-07-07T14:25:42.724+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-07T14:25:42.746+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fin_cotacoes_bcb_classic.transform scheduled__2025-03-03T00:00:00+00:00 [queued]>
[2025-07-07T14:25:42.752+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fin_cotacoes_bcb_classic.transform scheduled__2025-03-03T00:00:00+00:00 [queued]>
[2025-07-07T14:25:42.752+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-07-07T14:25:42.761+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform> on 2025-03-03 00:00:00+00:00
[2025-07-07T14:25:42.768+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=72978) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-07T14:25:42.768+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fin_cotacoes_bcb_classic', 'transform', 'scheduled__2025-03-03T00:00:00+00:00', '--job-id', '2093', '--raw', '--subdir', 'DAGS_FOLDER/cotacoes.py', '--cfg-path', '/tmp/tmpqo4s6hu3']
[2025-07-07T14:25:42.768+0000] {standard_task_runner.py:63} INFO - Started process 73000 to run task
[2025-07-07T14:25:42.768+0000] {standard_task_runner.py:91} INFO - Job 2093: Subtask transform
[2025-07-07T14:25:42.802+0000] {task_command.py:426} INFO - Running <TaskInstance: fin_cotacoes_bcb_classic.transform scheduled__2025-03-03T00:00:00+00:00 [running]> on host bc96ca91d307
[2025-07-07T14:25:42.884+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fin_cotacoes_bcb_classic' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-03T00:00:00+00:00'
[2025-07-07T14:25:42.886+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-07T14:25:42.895+0000] {cotacoes.py:63} WARNING - Nenhum dado recebido da tarefa de extração. Pulando transformação.
[2025-07-07T14:25:42.896+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-07T14:25:42.896+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-07T14:25:42.904+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=fin_cotacoes_bcb_classic, task_id=transform, run_id=scheduled__2025-03-03T00:00:00+00:00, execution_date=20250303T000000, start_date=20250707T142542, end_date=20250707T142542
[2025-07-07T14:25:42.941+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-07T14:25:42.950+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
